name: Feature request
description: Propose an enhancement
labels: [feature]
body:
  - type: textarea
    id: usecase
    attributes: {label: Use case / user story}
  - type: textarea
    id: acceptance
    attributes: {label: Acceptance criteria}
